### ISSUE TITLE
An orderable dated collection can't be custom sorted

### ISSUE THREAD

**Issue by robdekort** [statamic/eloquent-driver#139]
When you have a dated orderable collection you can't custom sort it. Well you can in the UI but the order won't persist. 

Was talking about this on Discord and it turns out @ryanmitchell already made a PR.

**Comment by robdekort** [comment]
An update on this. It turns out Ryan fixed a bug that is a bug but not this one. 

I'm storing my collection info in flat files but my entries in the database. This seems to be a bad combo.

**Comment by jasonvarga** [comment]
When saving the tree, there's an event listener that is supposed to update the `order` values for any entries that were moved.

It seems to be working fine, but I haven't tried the flat file / eloquent combo like Rob. I don't see why it wouldn't be doing it, though.

**Comment by jasonvarga** [comment]
Ok yeah it's a little more obvious now that I've tried it.

It ends up calling `CollectionRepository::updateEntryOrder()` - but since the collection is in the Stache, it does the Stache specific stuff.

A similar thing would happen if you stored collections in the db but entries in files (but you wouldn't because that's weird).

**Comment by ryanmitchell** [comment]
Yeah rob causes all sorts of problems. Do we need to move that call to the facade somehow?

**Comment by robdekort** [comment]
Hey Mitchell! I’m out camping. Stop blaming me! I didn’t even bring my computer.
