### ISSUE TITLE
Can't use `blueprint` as GraphQL filter

### ISSUE THREAD

**Issue by meandersen** [statamic/eloquent-driver#289]
### Bug description

After we have updated from Statamic 3.4 to 4.0, we got an issue with graphql. 
When we call entries and uses blueprint as a filter, we are ending up with an empty array of entries. Status, collection and parent works fine when we use them in filters.

### How to reproduce

graphql.php
```
'resources' => [
        'collections' => [
            '*' => [
                'enabled' => true, // All collection queries enabled
                'allowed_filters' => ['status', 'collection', 'parent', 'blueprint'], // With filters enabled for all
            ],
        ],
        'navs' => true,
        'taxonomies' => true,
        'assets' => true,
        'globals' => true,
        'sites' => true,
        'users' => false,
    ],
```

Query
```
query myQuery {
  entries(
    collection: "basic_pages"
    filter: {
      status: { in: "published" }
      blueprint: "blueprint_one"
    }
    sort: "publication_date desc"
  ) {
    data {
      __typename
      blueprint
      title
      status
    }
}
```

Result with blueprint
```
{
  "data": {
    "entries": {
      "data": []
    }
  }
}
```

Result without blueprint
```
{
  "data": {
    "entries": {
      "data": [
        {
          "__typename": "Entry_BasicPages_BlueprintOne",
          "blueprint": "blueprint_one",
          "title": "Foo",
          "status": "published"
        },
        {
          "__typename": "Entry_BasicPages_BlueprintTwo",
          "blueprint": "blueprint_two",
          "title": "Bar",
          "status": "published"
        },
        {
          "__typename": "Entry_BasicPages_BlueprintOne",
          "blueprint": "blueprint_one",
          "title": "Foo two",
          "status": "published"
        },
...
```

### Environment

```yaml
Statamic version: 4.48.0
Laravel Version: 9.52.16
PHP Version: 8.1.26
Composer Version: 2.7.6
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
I've just taken a look into this, using the latest version of Statamic and the Eloquent Driver.

In my testing, it actually seems like its the `status` filter causing issues, not the `blueprint` filter. When I comment out the `blueprint` filter in my query, I still get no results returned.

I believe this may be happening due to the fact you're querying the status using the `in` condition, rather than the `equals` condition, which we'd recommend for querying statuses.

Obviously, by using the `equals` condition, it *does* mean you can only query a single status at a time. From your example, it doesn't look like you need to query multiple statuses at once, but if you do, you'd have to split each status into it's own GraphQL query and use `equals`.
