### ISSUE TITLE
Editing parents of mounted entries don't always update child entry uris

### ISSUE THREAD

**Issue by jesseleite** [statamic/eloquent-driver#30]
- When editing the slug of a parent to a set of mounted entries, child uris are not updated
- When editing the tree nesting of a parent to a set of mounted entries, child uris are not updated

This is because eloquent is much more heavy-handed about filtering ids for performance reasons, etc.  See https://github.com/statamic/eloquent-driver/blob/master/src/Entries/CollectionRepository.php#L13-L15...

```php
if ($ids) {
    $query->whereIn('id', $ids);
}
```

Though I created the issue here, I'm wondering if the best fix might be in Statamic core; Maybe we could pass a smarter list of `$ids` into this function, taking mounted entries into account.

**Comment by AndrewHaine** [comment]
'Ello, Just a small update on this in case anyone follows the temporary solution, I've got a multisite instance approaching 2000 entries and the solution of calling `updateEntryUris()` on every saved event is having some performance implications (i.e. the page doesn't respond for a few seconds after the entry change is made).

A couple of ideas which may solve this:

**[Statamic Core] Allow us to update the uris for collection entries per site** 
Allow passing a site handle into `updateEntryUris()` so that only entries in the affected site are updated. I'm not immediately sure this is possible with how the stache works though.

**[Statamic Core] Attach the original data to ContentSaved events**
There's an open FR for this in `statamic/ideas` ([#7](https://github.com/statamic/ideas/issues/7)), this would allow us to check the `slug` and only update the entry URIs if it has changed.

**Comment by bognarlaszlo** [comment]
@jesseleite how we should proceed with this one? I'm guessing we should open up an issue at Statamic Core, however I'm not positive of which part of this issue should be handled in Core and which part in this driver.

**Comment by jasonvarga** [comment]
No need to open a separate issue. We'll tackle both sides.

**Comment by ryanmitchell** [comment]
This issue seems stale to me at this point - entry uris are definitely updating for me in 2.1.0 and Statamic 4.
I'm going to close this, but feel free to re-open if its still an issue.
